### ISSUE TITLE
[BUG] conn.requestPairingCode is not a function

### ISSUE THREAD

**Issue by Aal-oss** [WhiskeySockets/Baileys#434]

**Comment by Aal-oss** [comment]
i use whiskeysockets/baileys 6.5.0 is not working
in 6.4.1 is working

**Comment by Riders004** [comment]
> i use whiskeysockets/baileys 6.5.0 is not working in 6.4.1 is working

It's working in 6.5.0 also

**Comment by Aal-oss** [comment]
okay
